name: Build Tauri DEB and AppImage

on:
  push:
    branches: [ main ]

jobs:
  # Your existing DEB build works fine
  build-deb:
    if: "!contains(github.event.head_commit.message, '[skip ci deb]')"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 24.4.1
        uses: actions/setup-node@v4
        with:
          node-version: 24.4.1
      - name: Set up Rust 1.88
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0
      - name: Install system dependencies for Tauri
        run: |
          sudo apt update
          sudo apt install -y build-essential \
                              curl \
                              wget \
                              libssl-dev \
                              libgtk-3-dev \
                              squashfs-tools \
                              libayatana-appindicator3-dev \
                              librsvg2-dev \
                              libglib2.0-dev \
                              libsoup-3.0-dev \
                              libwebkit2gtk-4.1-dev \
                              gir1.2-webkit2-4.1 \
                              gir1.2-javascriptcore-4.1 \
                              libwebkit2gtk-4.1-0 \
                              libjavascriptcoregtk-4.1-0
      - name: Install frontend dependencies
        run: npm ci
      - name: Build Tauri app (DEB only)
        run: npm run tauri build -- --bundles deb
      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: Postchild-deb
          path: src-tauri/target/release/bundle/deb/*.deb
