name: Build Tauri DEB and AppImage

on:
  push:
    branches: [ main ]

jobs:
  # Your existing DEB build works fine
  build-deb:
    if: "!contains(github.event.head_commit.message, '[skip ci deb]')"
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js 24.4.1
        uses: actions/setup-node@v4
        with:
          node-version: 24.4.1
      - name: Set up Rust 1.88
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.88.0
      - name: Install system dependencies for Tauri
        run: |
          sudo apt update
          sudo apt install -y build-essential \
                              curl \
                              wget \
                              libssl-dev \
                              libgtk-3-dev \
                              squashfs-tools \
                              libayatana-appindicator3-dev \
                              librsvg2-dev \
                              libglib2.0-dev \
                              libsoup-3.0-dev \
                              libwebkit2gtk-4.1-dev \
                              gir1.2-webkit2-4.1 \
                              gir1.2-javascriptcore-4.1 \
                              libwebkit2gtk-4.1-0 \
                              libjavascriptcoregtk-4.1-0
      - name: Install frontend dependencies
        run: npm ci
      - name: Build Tauri app (DEB only)
        run: npm run tauri build -- --bundles deb
      - name: Upload DEB artifact
        uses: actions/upload-artifact@v4
        with:
          name: Postchild-deb
          path: src-tauri/target/release/bundle/deb/*.deb

  # Docker-based AppImage build for compatibility
  build-appimage-docker:
    if: "!contains(github.event.head_commit.message, '[skip ci appimage]')"
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup build environment
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt-get update
          apt-get install -y curl wget build-essential pkg-config software-properties-common
          
          # Install Node.js
          curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs
          
          # Install Rust
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
          
          # Add PPA for webkit 4.1 on Ubuntu 20.04
          add-apt-repository -y ppa:webkit-team/ppa
          apt-get update
          
          # Install Tauri dependencies
          apt-get install -y \
            libssl-dev \
            libgtk-3-dev \
            libwebkit2gtk-4.1-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            patchelf \
            libfuse2 \
            file
      
      - name: Build AppImage
        run: |
          source $HOME/.cargo/env
          npm ci
          npm run tauri build -- --bundles appimage
          chmod +x src-tauri/target/release/bundle/appimage/*.AppImage
      
      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Postchild-AppImage-universal
          path: src-tauri/target/release/bundle/appimage/*.AppImage
